sudo: false
language: node_js

node_js:
  - "12"
  - "10"
  - "8"

script:
  - npm run lint;

deploy:
- provider: npm
  email: "info@deepstream.io"
  api_key: ${NPM_TOKEN}
  skip_cleanup: true
  on:
    tags: true
    node_js: '10'

notifications:
  email: false
